
INSERT INTO friendship_statuses (name)
VALUES
  ('lorem,'),
  ('congue'),
  ('netus'),
  ('mollis'),
  ('Morbi'),
  ('nibh.'),
  ('rhoncus.'),
  ('sapien'),
  ('natoque'),
  ('turpis.');
INSERT INTO friendship_statuses (name)
VALUES
  ('magna.'),
  ('Integer'),
  ('tincidunt,'),
  ('ante'),
  ('erat,'),
  ('ante'),
  ('Aliquam'),
  ('facilisis,'),
  ('penatibus'),
  ('erat.');
INSERT INTO friendship_statuses (name)
VALUES
  ('Curabitur'),
  ('justo.'),
  ('Phasellus'),
  ('eu'),
  ('ridiculus'),
  ('in'),
  ('fringilla'),
  ('blandit'),
  ('eget'),
  ('tellus');
INSERT INTO friendship_statuses (name)
VALUES
  ('imperdiet,'),
  ('ut'),
  ('Maecenas'),
  ('lacus.'),
  ('volutpat'),
  ('Maecenas'),
  ('eros'),
  ('egestas'),
  ('eu,'),
  ('Duis');
INSERT INTO friendship_statuses (name)
VALUES
  ('libero'),
  ('varius.'),
  ('ac'),
  ('metus.'),
  ('urna.'),
  ('sapien.'),
  ('gravida.'),
  ('in'),
  ('Phasellus'),
  ('metus');
INSERT INTO friendship_statuses (name)
VALUES
  ('sit'),
  ('tincidunt,'),
  ('vitae'),
  ('lectus'),
  ('a,'),
  ('ultrices'),
  ('faucibus'),
  ('egestas.'),
  ('aliquet'),
  ('Pellentesque');
INSERT INTO friendship_statuses (name)
VALUES
  ('magna'),
  ('sit'),
  ('magna'),
  ('sapien.'),
  ('vestibulum'),
  ('sociis'),
  ('ligula.'),
  ('Nullam'),
  ('Quisque'),
  ('nascetur');
INSERT INTO friendship_statuses (name)
VALUES
  ('Nunc'),
  ('neque.'),
  ('nascetur'),
  ('ornare'),
  ('amet'),
  ('tincidunt'),
  ('varius'),
  ('a'),
  ('orci'),
  ('et,');
INSERT INTO friendship_statuses (name)
VALUES
  ('hendrerit'),
  ('aptent'),
  ('sagittis.'),
  ('feugiat'),
  ('fringilla'),
  ('Nulla'),
  ('tellus'),
  ('sapien,'),
  ('rutrum'),
  ('ac,');
INSERT INTO friendship_statuses (name)
VALUES
  ('montes,'),
  ('mollis.'),
  ('risus.'),
  ('fermentum'),
  ('pede.'),
  ('elit.'),
  ('Nam'),
  ('vehicula.'),
  ('pharetra'),
  ('ante');
